name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2
      - name: build and test
        run: |
          rsync -av ./~/ros2_setup_scripts/ros2_ws/src/usage_tracker
          cd /ros2_setup_scripts/ros2_ws
          bash -xv ./src/usage_tracker/test/test.bash /ros2_setup_scripts
